---
- name: Create deployment user
  user:
    name: deploy
    groups:
      - caddy
    append: true
    state: present
    home: "{{ webroot }}"
    password: "*"

- name: Create deployment SSH directory
  file:
    name: "{{ webroot }}/.ssh/"
    mode: 0700
    owner: deploy
    group: deploy
    state: directory

- name: Enroll deployment SSH keys
  lineinfile:
    dest: "{{ webroot }}/.ssh/authorized_keys"
    insertafter: "EOF"
    line: "{{ deploy_ssh_pubkey }}"
    create: true
    owner: deploy
    group: deploy
    mode: "0600"
    state: present

- name: Install rsync
  package:
    name: rsync
    state: present
