---
- name: Install Caddy from packages
  package:
    name: caddy
    state: present

- name: Create server directories
  file:
    name: "{{ webroot }}"
    state: directory
    owner: deploy
    group: caddy
    mode: "0755"

- name: Copy Caddyfile
  template:
    src: Caddyfile.j2
    dest: /etc/caddy/Caddyfile
    owner: root
    group: root
    mode: "664"
  notify: Caddyfile changed

- name: Ensure Caddy service is running
  systemd:
    name: caddy
    enabled: true
    state: started
