---
- name: Install wireguard-tools package
  package:
    name: wireguard-tools
    state: present

- name: Enable IP forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    sysctl_set: true
    reload: true

- name: Create Wireguard configuration directory
  file:
    name: "/etc/wireguard/"
    state: directory
    owner: root
    group: root
    mode: "0700"

- name: Generate wireguard config file
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
    owner: root
    group: root
    mode: "0700"

- name: Start wireguard service
  systemd:
    name: wg-quick@wg0
    enabled: true
    state: started
